### ISSUE TITLE
Input file issue

### ISSUE THREAD

**Issue by hasindu2008** [TaekAndBrendan/easyfm#1]
Hi

I just randmly came accross your preprint and gave you tool a try. However, I am getting the following error when trying to convert a FASTQ->FASTA. Any thoughts on why?

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/12987163/171317026-1a1eb947-9bf7-4e9e-86b6-435fcdc16a05.png">

By the way how was the software packaging done? It was great that the whole thing just worked without me having to install a million of other dependencies. Is this software packaging method applicable to Linux and MacOS as well?

Another random thought - do you have an plans to support nanopore raw signal data?

Regards

**Comment by TaekAndBrendan** [comment]
HI, Hasindu,

Thank you for using our app.

Could you please change your file extension like 'reads.fq' or 'reads.fastaq'? Because we support only 'fq' or 'fastaq' file extension. Let me add 'fastq' extension soon.

We are using 'cx-Freeze' to make software package. I developed this on linux. You might be able to use 'cx-Freeze' on linux.

Yes, if you give some ideas, we will update them.

Cheers,
Brendan.

________________________________
From: Hasindu Gamaarachchi ***@***.***>
Sent: Wednesday, 1 June 2022 12:47 PM
To: TaekAndBrendan/easyfm ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TaekAndBrendan/easyfm] Input file issue (Issue #1)


Hi

I just randmly came accross your preprint and gave you tool a try. However, I am getting the following error when trying to convert a FASTQ->FASTA. Any thoughts on why?

[image]<https://user-images.githubusercontent.com/12987163/171317026-1a1eb947-9bf7-4e9e-86b6-435fcdc16a05.png>

By the way how was the software packaging done? It was great that the whole thing just worked without me having to install a million of other dependencies. Is this software packaging method applicable to Linux and MacOS as well?

Another random thought - do you have an plans to support nanopore raw signal data?

Regards

**Comment by hasindu2008** [comment]
Oh yeh. That worked. 

Perhaps, an easy one to start with would be to extract the records for a list of given read IDs from a raw signal data file. You could easily do that without [SLOW5 format](https://www.nature.com/articles/s41587-021-01147-4) and the associated library [https://github.com/hasindu2008/slow5lib] and toolkit [https://github.com/hasindu2008/slow5tools].

Converting to/from FAST5<->BLOW5<->POD5 might be another cool possibility. But would be a bit hard with POD5 as it is still a bit hard to get it installed.

**Comment by TaekAndBrendan** [comment]
Thank you.

We are currently considering about next version.
That is a great idea. I will discuss about your suggestion with my co-workers.

Cheers,
Brendan.
________________________________
